version: "3"
services:
  centos7igbinaryphp81:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
        image: php-apcu-8.1
  stream8igbinaryphp81:
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS8
        image: php-apcu-8.1

volumes:
  rpm7:
    name: rpm7
  rpm8stream:
    name: rpm8stream