version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.8

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  igbinarybuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7igbinary
          build_service: centos7igbinary
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8igbinary
          build_service: centos8igbinary
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7igbinaryphp81
          build_file: docker-compose.php81.yml
          build_service: centos7igbinaryphp81
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8igbinaryphp81
          build_file: docker-compose.php81.yml
          build_service: centos8igbinaryphp81
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7igbinaryphp80
          build_file: docker-compose.php80.yml
          build_service: centos7igbinaryphp80
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8igbinaryphp80
          build_file: docker-compose.php80.yml
          build_service: centos8igbinaryphp80
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7igbinaryphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos7igbinaryphp74build
          requires:
            - centos7igbinary
      - docker-rpmbuild/image:
          name: centos8igbinaryphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos8igbinaryphp74build
          requires:
            - centos8igbinary
      - docker-rpmbuild/image:
          name: centos7igbinaryphp81build
          compose_file: build/php81/docker-compose.yml
          build_service: centos7igbinaryphp81build
          requires:
            - centos7igbinaryphp81
      - docker-rpmbuild/image:
          name: centos8igbinaryphp81build
          compose_file: build/php81/docker-compose.yml
          build_service: centos8igbinaryphp81build
          requires:
            - centos8igbinaryphp81
      - docker-rpmbuild/image:
          name: centos7igbinaryphp80build
          compose_file: build/php80/docker-compose.yml
          build_service: centos7igbinaryphp80build
          requires:
            - centos7igbinaryphp80
      - docker-rpmbuild/image:
          name: centos8igbinaryphp80build
          compose_file: build/php80/docker-compose.yml
          build_service: centos8igbinaryphp80build
          requires:
            - centos8igbinaryphp80

